branch-defaults:
  main:
    environment: AMPLIFI-env
environment-defaults:
  AMPLIFI-env:
    branch: null
    repository: null
global:
  application_name: AMPLIFI BETA
  default_ec2_keyname: AMPLIFI-SERVER
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: git
  workspace_type: Application
