name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWSACCESSKEYID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETACCESSKEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18

      - run: |
          npm install

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          aws --version
          pip install wheel
          pip install "Cython<3.0" "pyyaml<6" --no-build-isolation
          python3 -m pip install --upgrade pip
          pip install awsebcli --upgrade --user
          eb --version

      - run: |
          mkdir -p ~/.aws
          printf "[eb-cli]\naws_access_key_id=%s\naws_secret_access_key=%s\nregion=%s\n" "${{ secrets.AWSACCESSKEYID }}" "${{ secrets.AWSSECRETACCESSKEY }}" "us-east-1" > ~/.aws/credentials
          cat ~/.aws/credentials

      - run: |
          eb use ARCH-E-env-Test --region us-east-1
          eb deploy
